"""Sesion 8: tablas APU y APUItem

Revision ID: 84b496f68ba0
Revises: 
Create Date: 2026-06-09 16:47:17.488513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b496f68ba0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('subcategoria', sa.String(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('rendimiento', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apus_codigo'), 'apus', ['codigo'], unique=True)
    op.create_index(op.f('ix_apus_id'), 'apus', ['id'], unique=False)
    op.create_table('apu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apu_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('es_herramienta_menor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['apu_id'], ['apus.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apu_items_id'), 'apu_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apu_items_id'), table_name='apu_items')
    op.drop_table('apu_items')
    op.drop_index(op.f('ix_apus_id'), table_name='apus')
    op.drop_index(op.f('ix_apus_codigo'), table_name='apus')
    op.drop_table('apus')
    # ### end Alembic commands ###
